# Generated by Django 5.2.3 on 2025-07-06 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_orderitem_price_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
